name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            ext: ""
          - target: x86_64-pc-windows-gnu
            ext: ".exe"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install MinGW (for Windows target)
        if: matrix.target == 'x86_64-pc-windows-gnu'
        run: sudo apt-get update && sudo apt-get install -y mingw-w64

      - name: Build release binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Create or update release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: |
          gh release create "$TAG" \
            --repo="${{ github.repository }}" \
            --title="PDF Cutter ${TAG#v}" \
            --generate-notes \
            || echo "Release already exists"

      - name: Upload binaries to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ github.ref_name }}" \
            "target/${{ matrix.target }}/release/pdf-cutter${{ matrix.ext }}" \
            --repo="${{ github.repository }}" \
            --clobber
