name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="PDF Cutter ${tag#v}" \
              --generate-notes

  build-and-upload:
    name: Build ${{ matrix.target }}
    needs: create-release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            ext: .exe
          - target: x86_64-unknown-linux-musl
            ext: ""
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-rust@v2
        with:
          rust-version: stable
          target: ${{ matrix.target }}

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ github.ref_name }}" \
            "target/${{ matrix.target }}/release/pdfcutter${{ matrix.ext }}" \
            --repo="${{ github.repository }}"